Drop GIT_SSH_COMMAND from the wrapper
It breaks on Silverblue with:

 ./common/scripts/pattern-util.sh make push-secrets                                                                                                          ─╯
  Error: unknown shorthand flag: 'o' in -o
  See 'podman run --help'