Simplify the passing of KUBECONFIG
According to `man podman run` if we simply pass `-e KUBECONFIG` to
the podman invocation: "If an environment variable is spec‐
ified without a value, Podman checks the host environment for a value
and set the variable only if it is set on the host"

So let's just do that and drop the current more complex fragile logic.

Tested with:

* No KUBECONFIG set
unset KUBECONFIG; ./pattern.sh make install
make -f common/Makefile operator-deploy
make[1]: Entering directory '/home/michele/Engineering/cloud-patterns/multicloud-gitops'
Checking prerequisites:
  Check for 'git helm oc ansible': OK
  Check for python-kubernetes: OK
  Check for kubernetes.core collection: OK
Checking repository:
  https://github.com/mbaldessari/multicloud-gitops.git - branch script-fix: Running inside a container: Skipping git ssh checks
Running helm:
Error: Kubernetes cluster unreachable: Get "https://localhos:6443/version"

* With KUBECONFIG set
export KUBECONFIG=~/sno1-kubeconfig
./pattern.sh make install
make -f common/Makefile operator-deploy
make[1]: Entering directory '/home/michele/Engineering/cloud-patterns/multicloud-gitops'
Checking prerequisites:
  Check for 'git helm oc ansible': OK
  Check for python-kubernetes: OK
  Check for kubernetes.core collection: OK
Checking repository:
  https://github.com/mbaldessari/multicloud-gitops.git - branch script-fix: Running inside a container: Skipping git ssh checks
Running helm:
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/michele/sno1-kubeconfig
Release "multicloud-gitops" does not exist. Installing it now.
NAME: multicloud-gitops
LAST DEPLOYED: Mon Sep  4 07:04:16 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
make[1]: Leaving directory '/home/michele/Engineering/cloud-patterns/multicloud-gitops'
make load-secrets
make[1]: Entering directory '/home/michele/Engineering/cloud-patterns/multicloud-gitops'
make -f common/Makefile load-secrets
...